CREATE TABLE posts (
    id INTEGER NOT NULL,
	title VARCHAR(100) NOT NULL,
	content TEXT NOT NULL,
	date_posted DATETIME NOT NULL,
	author VARCHAR(20) NOT NULL,
	PRIMARY KEY (id)
);

CREATE TABLE users(
    id INTEGER NOT NULL,
	name VARCHAR(100),
	email VARCHAR(100),
	PRIMARY KEY (id)
);